### PR TITLE
Hide powershell window using window creation flags in Windows

### PR DESCRIPTION
**Pull request by jknightmmcs**
A new version of hiding PowerShell window.

Why did I need it?

1. Raw version, without all changes, was showing the PowerShell window during its execution all the time.
2. The first version of hidden_powershell_window indeed hides it, but, as it was noticed by our QA engineer, creates a little "blink" before disappearing, that messes up with the current focus of the application.
2. This, second version, creates a console window with a [0x80000000 (CREATE_NO_WINDOW)](https://docs.microsoft.com/en-us/windows/win32/procthread/process-creation-flags) flag, which will be invisible for certain.

P.S.  _-WindowStyle Hidden_ changes are rolled back.

### CODE REVIEW

**Comment by jknightmmcs** [comment]
Small bug found, will fix it tomorrow.

**Comment by jknightmmcs** [comment]
The bug is fixed, now seems to work correctly.

**Comment by cfsamson** [comment]
LGTM.

> P.S. This is why you should never do programming at 2:00 AM.

Been there, done that 😄

**Comment by jknightmmcs** [comment]
Updated! 👍

**Pull request merged**
